### ISSUE TITLE
Speed benchmark

### ISSUE THREAD

**Issue by lorepieri8** [fentec-project/CiFEr#19]
It would be good to have in the README a basic time benchmark, like time to encrypt/decrypt a vector and time to compute an inner product of two vectors.

Do you already have some time benchmarks which you could share? 
I'm particularly interested in a full encrypt/decrypt/evaluate-inner-product cycle for the case of 128 float vectors.

This might be inspirational for a future benchmark file: https://github.com/microsoft/SEAL/blob/master/native/examples/6_performance.cpp

**Comment by tilenmarc** [comment]
Hi! Thanks for a suggestion. We will try to do it in the near future.
For now you can look at [this paper](https://eprint.iacr.org/2019/1129.pdf) where we did some benchmarks. Another simple option is that you simply modify a test that we have written for every scheme to fit your parameters and see approximate time.
But note the following: there is no practical FE scheme that works good with floats, only schemes that work over integers or modular arithmetic. So you would need to discretize floats into integers. Moreover if your values are big (say above 2^20), then Paillier scheme is the only practical one. This is the case since most of the others have a discrete logarithm calculation in the decryption, which is a hard problem for big values.

**Comment by lorepieri8** [comment]
The paper answers to my question, thanks.
